### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by Annyya** [microsoftgraph/msgraph-training-optimize-network-traffic#6]
Hi, 
I am currently learning dotnet application development. I am doing the tutorial with a newly created development tenant. Here the MFA seems to be enabled by default. Unfortunately this leads to a problem with the login. In the tutorial there is no mention of the MFA at any point. Any help would be appreciated.

Following the error message: 

System.AggregateException: One or more errors occurred. (AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.
Trace ID: a1668388-34cb-4995-ae13-a4f297c79600
Correlation ID: 52279df7-0f5b-4c93-b47c-01dbd5364268
Timestamp: 2020-11-17 17:15:28Z)
 ---> MSAL.NetCore.4.22.0.0.MsalUiRequiredException:
        ErrorCode: invalid_grant
Microsoft.Identity.Client.MsalUiRequiredException: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.
Trace ID: a1668388-34cb-4995-ae13-a4f297c79600
Correlation ID: 52279df7-0f5b-4c93-b47c-01dbd5364268
Timestamp: 2020-11-17 17:15:28Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByUsernamePasswordParameters usernamePasswordParameters, CancellationToken cancellationToken)
   at Helpers.MsalAuthenticationProvider.GetTokenAsync() in C:\Users\...\Documents\Projects\microsoft-graph-learn\graphconsoleapp\MsalAuthenticationProvider.cs:line 62
   at Helpers.MsalAuthenticationProvider.AuthenticateRequestAsync(HttpRequestMessage request) in C:\Users\...\Documents\Projects\microsoft-graph-learn\graphconsoleapp\MsalAuthenticationProvider.cs:line 40
   at Helpers.AuthHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\...\Documents\Projects\microsoft-graph-learn\graphconsoleapp\AuthHandler.cs:line 20
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
        StatusCode: 400
        ResponseBody: {"error":"invalid_grant","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.\r\nTrace ID: a1668388-34cb-4995-ae13-a4f297c79600\r\nCorrelation ID: 52279df7-0f5b-4c93-b47c-01dbd5364268\r\nTimestamp: 2020-11-17 17:15:28Z","error_codes":[50076],"timestamp":"2020-11-17 17:15:28Z","trace_id":"a1668388-34cb-4995-ae13-a4f297c79600","correlation_id":"52279df7-0f5b-4c93-b47c-01dbd5364268","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: 52279df7-0f5b-4c93-b47c-01dbd5364268
x-ms-request-id: a1668388-34cb-4995-ae13-a4f297c79600
x-ms-ests-server: 2.1.11198.15 - AMS2 ProdSlices
x-ms-clitelem: 1,50076,0,,
Set-Cookie: fpc=AmTzqwCmb5lLpkB-0AXopG_EC1SZAQAAAC_8RdcOAAAA; expires=Thu, 17-Dec-2020 17:15:28 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=prod; path=/; secure; httponly, stsservicecookie=ests; path=/; secure; samesite=none; httponly
Date: Tue, 17 Nov 2020 17:15:28 GMT

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at graphconsoleapp.Program.<>c__DisplayClass0_0.<Main>b__0() in C:\Users\...\Documents\Projects\microsoft-graph-learn\graphconsoleapp\Program.cs:line 47

**Comment by jasonjoh** [comment]
@andrewconnell as FYI

Which part are you doing when you hit this error? Looking at the first part, it seems to be doing ROPC flow which isn't interactive, so it bypasses any MFA configuration. It may be better to switch over to device code flow - see https://docs.microsoft.com/graph/tutorials/dotnet-core

**Comment by Annyya** [comment]
Hi Jason,
thanks a lot for the quick answer. I did the first tutorial Understand throttling in Microsoft Graph. There the above described error occurred during authentication.

The linked tutorial with the Divice Code Flow works for me. Thanks for the hint.

**Comment by jasonjoh** [comment]
Closing as ROPC has been removed from this.
